publish:
  docker:
    username: $$DOCKER_USERNAME
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    registry: registry.aliyuncs.com
    repo: xiaolu-img/xiaolusys-base
    tag: forum
    file: Dockerfile
    mirror: https://n5fb0zgg.mirror.aliyuncs.com
    tag: $$COMMIT

